# Generated by Django 2.2 on 2023-07-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230713_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
