# Generated by Django 2.2 on 2023-07-30 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_category_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='show',
        ),
    ]
