# Generated by Django 2.2 on 2023-09-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_restaurantimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.FloatField()),
                ('encode', models.CharField(max_length=255)),
                ('status', models.BooleanField()),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='prices',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
