# Generated by Django 2.2 on 2023-09-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_restaurant_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='kitchen',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='average',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
