# Generated by Django 2.2 on 2023-09-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20230920_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='novy',
            field=models.BooleanField(default=False),
        ),
    ]
