# Generated by Django 2.2 on 2023-09-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_restaurant_novy'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='user_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
