# Generated by Django 2.2 on 2023-09-22 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_otklik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('experiece', models.CharField(max_length=255)),
                ('skills', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('category_id', models.CharField(max_length=255)),
                ('subcategory', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('file', models.FileField(upload_to='')),
                ('otkliki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Otklik')),
            ],
        ),
    ]
