# Generated by Django 2.2 on 2023-09-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otklik',
            name='job',
        ),
        migrations.RemoveField(
            model_name='order',
            name='otkliki',
        ),
        migrations.AddField(
            model_name='order',
            name='otkliki',
            field=models.ManyToManyField(default=None, to='core.Otklik'),
        ),
    ]
