# Generated by Django 2.2 on 2023-09-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20230923_0506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='experiece',
            new_name='experience',
        ),
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.CharField(default='Almaty', max_length=255),
        ),
    ]
