# Generated by Django 2.2 on 2023-09-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20230924_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='restaurants',
            field=models.ManyToManyField(default=None, null=True, to='core.Restaurant'),
        ),
    ]
